# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cantango-config}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Kristian Mandrup}]
  s.date = %q{2011-12-20}
  s.description = %q{Configuration DSL for configuring CanTango}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "cantango-config.gemspec",
    "lib/cantango/adapter/compiler.rb",
    "lib/cantango/adapter/moneta.rb",
    "lib/cantango/category.rb",
    "lib/cantango/class_methods.rb",
    "lib/cantango/config.rb",
    "lib/cantango/config/ability.rb",
    "lib/cantango/config/ability/engine.rb",
    "lib/cantango/config/ability/modes.rb",
    "lib/cantango/config/ability/modes/execution.rb",
    "lib/cantango/config/account.rb",
    "lib/cantango/config/accounts.rb",
    "lib/cantango/config/adapters.rb",
    "lib/cantango/config/autoload.rb",
    "lib/cantango/config/categories.rb",
    "lib/cantango/config/class_methods.rb",
    "lib/cantango/config/debug.rb",
    "lib/cantango/config/engines.rb",
    "lib/cantango/config/engines/available.rb",
    "lib/cantango/config/engines/order.rb",
    "lib/cantango/config/factory.rb",
    "lib/cantango/config/guest.rb",
    "lib/cantango/config/helpers.rb",
    "lib/cantango/config/hooks.rb",
    "lib/cantango/config/localhosts.rb",
    "lib/cantango/config/models.rb",
    "lib/cantango/config/models/actions.rb",
    "lib/cantango/config/models/active_record.rb",
    "lib/cantango/config/models/data_mapper.rb",
    "lib/cantango/config/models/generic.rb",
    "lib/cantango/config/models/mongo.rb",
    "lib/cantango/config/models/mongo_mapper.rb",
    "lib/cantango/config/models/mongoid.rb",
    "lib/cantango/config/orms.rb",
    "lib/cantango/config/user.rb",
    "lib/cantango/config/users.rb",
    "lib/cantango/config_ext.rb",
    "lib/cantango/config_ext/loader.rb",
    "lib/cantango/config_ext/loader/yaml.rb",
    "lib/cantango/registry.rb",
    "lib/cantango/registry/base.rb",
    "lib/cantango/registry/clazz.rb",
    "lib/cantango/registry/hash.rb",
    "spec/cantango/category_spec.rb",
    "spec/cantango/config/ability/modes/execution_spec.rb",
    "spec/cantango/config/ability/modes_spec.rb",
    "spec/cantango/config/ability_spec.rb",
    "spec/cantango/config/account_spec.rb",
    "spec/cantango/config/accounts_spec.rb",
    "spec/cantango/config/adapters_spec.rb",
    "spec/cantango/config/autoload_spec.rb",
    "spec/cantango/config/categories_spec.rb",
    "spec/cantango/config/class_methods_spec.rb",
    "spec/cantango/config/debug_spec.rb",
    "spec/cantango/config/engines/available_spec.rb",
    "spec/cantango/config/engines/engine_shared.rb",
    "spec/cantango/config/engines/order_spec.rb",
    "spec/cantango/config/engines_spec.rb",
    "spec/cantango/config/factory_spec.rb",
    "spec/cantango/config/guest/find_guest_default_way_spec.rb",
    "spec/cantango/config/guest_spec.rb",
    "spec/cantango/config/helpers_spec.rb",
    "spec/cantango/config/localhosts_spec.rb",
    "spec/cantango/config/models_spec.rb",
    "spec/cantango/config/orms_spec.rb",
    "spec/cantango/config/shared/factory_ex.rb",
    "spec/cantango/config/user_spec.rb",
    "spec/cantango/config/users_spec.rb",
    "spec/cantango/config_spec.rb",
    "spec/cantango/registry/base_spec.rb",
    "spec/cantango/registry/clazz_spec.rb",
    "spec/cantango/registry/hash_spec.rb",
    "spec/cantango/registry/shared/base_ex.rb",
    "spec/cantango/registry/shared/clazz_ex.rb",
    "spec/cantango/registry/shared/hash_ex.rb",
    "spec/db/database.yml",
    "spec/factories/project.rb",
    "spec/fixtures/models.rb",
    "spec/fixtures/models/admin.rb",
    "spec/fixtures/models/admin_account.rb",
    "spec/fixtures/models/items.rb",
    "spec/fixtures/models/permission.rb",
    "spec/fixtures/models/project.rb",
    "spec/fixtures/models/simple_roles.rb",
    "spec/fixtures/models/user.rb",
    "spec/fixtures/models/user_account.rb",
    "spec/migrations/001_create_projects.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/cantango-config}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Configuration for Cantango}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<sweetloader>, ["~> 0.1.6"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.2"])
      s.add_runtime_dependency(%q<cantango-core>, ["~> 0.1.9"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1"])
      s.add_dependency(%q<sugar-high>, [">= 0.6.1"])
      s.add_dependency(%q<sweetloader>, ["~> 0.1.6"])
      s.add_dependency(%q<hashie>, ["~> 1.2"])
      s.add_dependency(%q<cantango-core>, ["~> 0.1.9"])
      s.add_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1"])
    s.add_dependency(%q<sugar-high>, [">= 0.6.1"])
    s.add_dependency(%q<sweetloader>, ["~> 0.1.6"])
    s.add_dependency(%q<hashie>, ["~> 1.2"])
    s.add_dependency(%q<cantango-core>, ["~> 0.1.9"])
    s.add_dependency(%q<bundler>, [">= 1.1.rc"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
  end
end

